CC = gcc

CFLAGS = -pedantic -g                                                       

LDFLAGS = -pedantic -g
 
all: mush2
 
mush2: mush2.o
     $(CC) $(LDFLAGS) -L ~pn-cs357/Given/Mush/libmush/lib64 -o mush2 mush2.      o -lmush
 
 mush2.o: mush2.c
     $(CC) $(CFLAGS) -I ~pn-cs357/Given/Mush/libmush/include -c mush2.c
 
 clean:
     -rm *.o
